
<CrewMember>:
    orientation: 'horizontal'
    spacing: dp(10)
    size_hint_y: None
    height: dp(240)
    AsyncImage:
        source: root.pic
        keep_ratio: True
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.name
            color: 1, 0, 1, 1  # red color
            font_size: dp(26)
            size_hint_y: None
            height: dp(30)
        Label:
            text: "Country: " + root.country
            font_size: dp(18)
            size_hint_y: None
            height: dp(30)
        Label:
            text: "Title: " + root.jobtitle
            font_size: dp(18)
            size_hint_y: None
            height: dp(30)
        Label:
            text: "Mission: " + root.mission
            font_size: dp(18)
            size_hint_y: None
            height: dp(30)
        Label:
            text: "Time in Space: " + root.days_in_space + " days"
            font_size: dp(18)
            size_hint_y: None
            height: dp(30)


<BoxLayout>:
    spacing: dp(20)

<CrewList>:
    orientation: 'vertical'
    padding: dp(20)

    Label:
        text: root.title + " - Current ISS Crew"
        font_size: '30sp'
        size_hint_y: None
        height: '48dp'


    ScrollView:
        BoxLayout:
            id: crew_members
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(20)
